----------------------------------------------------
-- file : atmmain
-- copyright (c) 2009 Atempad  (atem.pad@mail.ru) 
-----------------------------------------------------

local ui_sleep_init = false;
local sleepingbag_id = nil;

----------------------------------------------------------------------------------
-- Func: Print in log file.
----------------------------------------------------------------------------------
function prnt(msg)
end

----------------------------------------------------------------------------------
-- Func: Callback on the load game.
----------------------------------------------------------------------------------
function on_game_load()
	atmanoms.dynanoms():level_spawn();
	atmmonster.sim_monsters():level_spawn();
--	atmdebug.fill_backpack();	
--	atmdebug.get_level_graphs()
end

----------------------------------------------------------------------------------
-- Func: Callback on the game end.
----------------------------------------------------------------------------------
function on_actor_destroy()
end

----------------------------------------------------------------------------------
-- Func: Callback on the take of item.
----------------------------------------------------------------------------------
function on_item_take(obj)
end

----------------------------------------------------------------------------------
-- Func: Callback on the loss of item.
----------------------------------------------------------------------------------
function on_item_drop(obj)

--	atmdebug.abundance(obj);	
end

----------------------------------------------------------------------------------
-- Func: Update of actor.
----------------------------------------------------------------------------------
function update()
---	atmsleep.update()

--	atmdebug.show_debuginfo();
end

----------------------------------------------------------------------------------
-- Func: Save a value in a storage.
----------------------------------------------------------------------------------
function save_val(varname, val)
	xr_logic.pstor_store(db.actor, varname, val);
end

----------------------------------------------------------------------------------
-- Func: Load a value from a storage.
----------------------------------------------------------------------------------
function load_val(varname, defval)
	xr_logic.pstor_retrieve(db.actor, varname, defval);
end

